image: golang:1.5

# Put the go sources in GOPATH
# This is required to make the vendor working
before_script:
- GODIR=$GOPATH/src/gitlab.com/gitlab-org/gitlab-pages
- mkdir -p "$(dirname "$GODIR")"
- ln -sfv "$(pwd -P)" "$GODIR"
- cd "$GODIR"

test:1.5:
  image: golang:1.5
  script:
  - make verify-lite
  - make acceptance

test:1.6:
  image: golang:1.6
  script:
  - make verify
  - make acceptance

test:1.7:
  image: golang:1.7
  script:
  - make verify
  - make acceptance
