image: golang:1.8

# Put the go sources in GOPATH
# This is required to make the vendor working
before_script:
- GODIR=$GOPATH/src/gitlab.com/gitlab-org/gitlab-pages
- mkdir -p "$(dirname "$GODIR")"
- ln -sfv "$(pwd -P)" "$GODIR"
- cd "$GODIR"

.test: &test
  script:
  - make verify
  - make acceptance


test:1.8:
  <<: *test
  
test:1.9:
  image: golang:1.9
  <<: *test
   